In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv('C:\\Users\\acer\\Deep Learning - Chetan Bhaiya\\data1.csv', header = None)
#print(df)
#print(df2)
df2 = pd.read_csv('C:\\Users\\acer\\Deep Learning - Chetan Bhaiya\\label1.csv', header = None)

data1 = np.asarray(df)
label1 = np.asarray(df2)

In [4]:
uniqueElements = np.unique(label1)

### One Hot Encoding


In [5]:
OHElabel = np.eye(len(uniqueElements))[label1]
print(OHElabel)


[[[0. 0. 0. 1. 0.]]

 [[0. 0. 1. 0. 0.]]

 [[0. 0. 1. 0. 0.]]

 ...

 [[0. 0. 1. 0. 0.]]

 [[0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]]]


In [6]:
print(np.shape(OHElabel))

(20000, 1, 5)


In [7]:
OHElabel = np.reshape(OHElabel,[20000,5])

In [8]:
np.shape(OHElabel)

(20000, 5)

### Dividing the data set into TRAINING-VALIDATION-TESTING

In [9]:
eightyP = int((0.8)*len(OHElabel))
tenP = int((0.1)*len(OHElabel))

trainingL = OHElabel[:eightyP]
validationL = OHElabel[eightyP: eightyP + tenP]
testingL = OHElabel[eightyP+tenP:]

trainingData = data1[:eightyP]
validationData = data1[eightyP: eightyP + tenP]
testingData = data1[eightyP+tenP:]

print(np.shape(trainingL))
print(np.shape(validationL))  
print(np.shape(testingL))

print(np.shape(trainingData))
print(np.shape(validationData))  
print(np.shape(testingData))

(16000, 5)
(2000, 5)
(2000, 5)
(16000, 20)
(2000, 20)
(2000, 20)


In [39]:
#initialising weights and biases
h = int(input())    #no of neurons in inputs hidden layer

10


In [101]:
b1 = np.zeros(h)    #20 biases of hidden layer
b2 = np.zeros(5)    #h biases of output layer

In [100]:
w1 = np.random.normal(0, 1/np.sqrt(20), (20,h))     #for layer 1
w2 = np.random.normal(0, 1/np.sqrt(h), (h,5))       #for hidden layer

In [53]:
def actFunc(haha,choose):
    if (choose==1):    #Sigmoid
        return (1/(1+np.exp(haha)))
    elif (choose==2):    #ReLU
        return np.max(0,haha)
    elif (choose==3):    #tanh
        return np.tanh(haha)
    elif (choose==4):    #softmax
        temp=np.exp(haha)
        return temp/np.sum(temp,axis=1,keepdims=True)

In [94]:
alpha = float(input())

0.001


In [61]:
#cost funtion
batch = int(input())

1000


In [56]:
#cross entropy function
def CostFun(y,t):
    return ( (1-t)*np.log(1-y) - t*np.log(y) )

In [63]:
def forwardFun(data):
    a0=data
    z1=np.dot(a0,w1)+b1
    a1=actFunc(z1,3)    #tanh
    z2=np.dot(a1,w2)+b2
    a2=actFunc(z2,4)    #we called softmax because we wanted the output of our last layer in probability
    return a0,a1,a2,z1,z2

In [79]:
#accuracy fun
def accuracyFun(output,labelData,dataSize):
    maxInRow=np.argmax(output, axis=1)
    maxInLabels=np.argmax(labelData, axis=1)
    haha=np.equal(maxInRow,maxInLabels)
    count=np.sum(haha)
    
    return (count/dataSize)*100

### Feed Forward 

In [105]:
for j in range (100):
    for i in range(int(len(trainingData)/batch)):
        #epoch
        #forward pass
        #print(w1.shape)
        #print(b1.shape)
        #print(trainingData[i*batch:(i+1)*batch, :].shape)
        a0,a1,a2,z1,z2 = forwardFun(trainingData[i*batch:(i+1)*batch, :])
        #backpass
        trainingLabelBatch = trainingL[i*batch:(i+1)*batch,:]
        y=a2
        del2=(y-trainingLabelBatch)    #for last layer
        del1=np.dot(del2,w2.T)*(1-pow(actFunc(z1,3),2))
        dcdw2=np.dot(a1.T,del2)
        dcdw1=np.dot(a0.T,del1)
        dcdb1=np.sum(del1,axis=0)
        dcdb2=np.sum(del2,axis=0)
    #     print("del2 = ",del2.shape)
    #     print("w2 = ",w2.shape)
    #     print("w1= ",w1.shape)
    #     print("del1 = ",del1.shape)
    #     print("a0 = ",a0.shape)
    #     print("a1 = ",a1.shape)
    #     print("dcdw1 = ",dcdw1.shape)

        w1=w1-alpha*dcdw1
        w2=w2-alpha*dcdw2
        b1=b1-alpha*dcdb1
        b2=b2-alpha*dcdb2

    #Cost after one epoch
    a0,z1,a1,z2,a2=forwardFun(trainingData)
    ytrue=a2
    cost=np.sum(CostFun(ytrue,trainingL))/16000
    print ("cost",cost)
    accuracy = accuracyFun(ytrue,trainingL,16000)
    print ("training accuracy",accuracy)

c:\python36\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


cost nan
training accuracy 91.58125
cost nan
training accuracy 91.59375
cost nan
training accuracy 91.59375
cost nan
training accuracy 91.60000000000001
cost nan
training accuracy 91.60000000000001
cost nan
training accuracy 91.60625
cost nan
training accuracy 91.60625
cost nan
training accuracy 91.60625
cost nan
training accuracy 91.61875
cost nan
training accuracy 91.63125
cost nan
training accuracy 91.6375
cost nan
training accuracy 91.63125
cost nan
training accuracy 91.61875
cost nan
training accuracy 91.6125
cost nan
training accuracy 91.625
cost nan
training accuracy 91.625
cost nan
training accuracy 91.63125
cost nan
training accuracy 91.61875
cost nan
training accuracy 91.63125
cost nan
training accuracy 91.63125
cost nan
training accuracy 91.63125
cost nan
training accuracy 91.64375
cost nan
training accuracy 91.66250000000001
cost nan
training accuracy 91.66875
cost nan
training accuracy 91.675
cost nan
training accuracy 91.66250000000001
cost nan
training accuracy 91.66875
